# [dbo].[Branch office]

In [0]:
/****** Object:  Table [dbo].[Branch office]    Script Date: 21.03.2025 14:22:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Branch office](
	[ID] [int] NULL,
	[Branch_code] [int] NOT NULL,
	[Branch_name] [nvarchar](30) NULL,
	[Address] [nvarchar](50) NULL,
	[Telephone] [nvarchar](12) NULL,
 CONSTRAINT [PK_Branch office] PRIMARY KEY CLUSTERED 
(
	[Branch_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Contracts]

In [0]:
/****** Object:  Table [dbo].[Contracts]    Script Date: 21.03.2025 14:22:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contracts](
	[ID] [int] NULL,
	[Contract_number] [nchar](10) NULL,
	[Date_of_conclusion] [date] NULL,
	[Sum_insured] [int] NULL,
	[Tariff_rate] [int] NULL,
	[Branch_code] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[Insurance view]

In [0]:
/****** Object:  Table [dbo].[Insurance view]    Script Date: 21.03.2025 14:22:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Insurance view](
	[ID] [int] NULL,
	[Insurance_type_code] [nchar](10) NOT NULL,
	[Name] [nvarchar](30) NULL,
 CONSTRAINT [PK_Insurance view] PRIMARY KEY CLUSTERED 
(
	[Insurance_type_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Branch office]

In [0]:
INSERT [dbo].[Branch office] ([ID], [Branch_code], [Branch_name], [Address], [Telephone]) VALUES (1, 120, N'Гардия', N'г. Москва, Ленинградское ш., д. 72', N'84599358950')
INSERT [dbo].[Branch office] ([ID], [Branch_code], [Branch_name], [Address], [Telephone]) VALUES (2, 125, N'Газпром страхование', N'г. Москва, пл. Тургеневская, д. 2/4 стр. 1', N'88001004440')
INSERT [dbo].[Branch office] ([ID], [Branch_code], [Branch_name], [Address], [Telephone]) VALUES (3, 130, N'НАСКО', N'г. Казань, ул. Чуйкова, д. 2Б', N'88005001616')
INSERT [dbo].[Branch office] ([ID], [Branch_code], [Branch_name], [Address], [Telephone]) VALUES (4, 135, N'Юнити страхование', N'г. Санкт-Петербург, пер. Кваренги, д. 4', N'88126002050')
INSERT [dbo].[Branch office] ([ID], [Branch_code], [Branch_name], [Address], [Telephone]) VALUES (5, 140, N'Росгосстрах', N'Нижегородская обл., г. Лукоянов, ул. Коммуны, 40А', N'88319643513')
GO

# [dbo].[Contracts]

In [0]:
INSERT [dbo].[Contracts] ([ID], [Contract_number], [Date_of_conclusion], [Sum_insured], [Tariff_rate], [Branch_code]) VALUES (1, N'65.11     ', CAST(N'2023-11-15' AS Date), 1500000, 10000, 125)
INSERT [dbo].[Contracts] ([ID], [Contract_number], [Date_of_conclusion], [Sum_insured], [Tariff_rate], [Branch_code]) VALUES (2, N'65.12.4   ', CAST(N'2024-01-25' AS Date), 2000000, 15000, 135)
INSERT [dbo].[Contracts] ([ID], [Contract_number], [Date_of_conclusion], [Sum_insured], [Tariff_rate], [Branch_code]) VALUES (3, N'65 12 2   ', CAST(N'2024-02-10' AS Date), 3000000, 25000, 140)
INSERT [dbo].[Contracts] ([ID], [Contract_number], [Date_of_conclusion], [Sum_insured], [Tariff_rate], [Branch_code]) VALUES (4, N'65 11     ', CAST(N'2024-04-24' AS Date), 1200000, 8000, 120)
INSERT [dbo].[Contracts] ([ID], [Contract_number], [Date_of_conclusion], [Sum_insured], [Tariff_rate], [Branch_code]) VALUES (5, N'65.12.2   ', CAST(N'2024-05-05' AS Date), 5000000, 50000, 130)
GO

# [dbo].[Insurance view]

In [0]:
INSERT [dbo].[Insurance view] ([ID], [Insurance_type_code], [Name]) VALUES (1, N'65 11     ', N'личное')
INSERT [dbo].[Insurance view] ([ID], [Insurance_type_code], [Name]) VALUES (2, N'65 12 2   ', N'имущественное')
INSERT [dbo].[Insurance view] ([ID], [Insurance_type_code], [Name]) VALUES (3, N'65.11     ', N'личное')
INSERT [dbo].[Insurance view] ([ID], [Insurance_type_code], [Name]) VALUES (4, N'65.12.2   ', N'имущественное')
INSERT [dbo].[Insurance view] ([ID], [Insurance_type_code], [Name]) VALUES (5, N'65.12.4   ', N'личное')
GO

# [FK_Contracts_Branch office]

In [0]:
ALTER TABLE [dbo].[Contracts]  WITH CHECK ADD  CONSTRAINT [FK_Contracts_Branch office] FOREIGN KEY([Branch_code])
REFERENCES [dbo].[Branch office] ([Branch_code])
GO
ALTER TABLE [dbo].[Contracts] CHECK CONSTRAINT [FK_Contracts_Branch office]
GO

# [FK_Contracts_Insurance view]

In [0]:
ALTER TABLE [dbo].[Contracts]  WITH CHECK ADD  CONSTRAINT [FK_Contracts_Insurance view] FOREIGN KEY([Contract_number])
REFERENCES [dbo].[Insurance view] ([Insurance_type_code])
GO
ALTER TABLE [dbo].[Contracts] CHECK CONSTRAINT [FK_Contracts_Insurance view]
GO